package davidkatanik.vsb.cz.gameUtils;

/**
 * Created by David on 07.11.2015.
 *
 */
public enum CardTypes {
    PLATOON, RIDER, RECRUIT, SABOTEUR, BANSHEE, ARCHER, SWAT, THIEF, CATAPULT, SORCERER, CONJURE_BRICKS, CONJURE_CRYSTALS, CONJURE_WEAPONS, DRAGON, CURSE, PIXIES, CRUSH_BRICKS, CRUSH_CRYSTALS, CRUSH_WEAPONS, BABYLON, FENCE, DEFENCE, FORT, WAIN, RESERVE,
    SCHOOL, TOWER, BASE, WALL,
}

